@host = http://localhost:5097

@token = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdXZ2IydHhnS0xuMTB3ZWtFT040USJ9.eyJpc3MiOiJodHRwczovL3R1YW5pdHByby51cy5hdXRoMC5jb20vIiwic3ViIjoiWmFURnVsTndDWmJqN0JhUmVmMEhlVWlucXBHcFNZWmxAY2xpZW50cyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QiLCJpYXQiOjE2Njg5NDA2OTAsImV4cCI6MTY2OTAyNzA5MCwiYXpwIjoiWmFURnVsTndDWmJqN0JhUmVmMEhlVWlucXBHcFNZWmwiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJwZXJtaXNzaW9ucyI6W119.fYBy8xdU1FNZ-eLMcPbYW13qnYGAPpVPy8QAbC4wm3gXhZXtU3KArblSPD52z1RzZcpEweYziB6yvY0AWzebzG5PWkyn-2B3Ezd3AYSZplTvXLqWl3D__1WFv9Qt5npvsNvH00gPn7YELbAO24mSdLdaWOzeO88gYnxNDvzek1FDxPKSBwjTUq6kbaSKD3N0yJZeXCuN2Gvci5wRh_-pQZRCByiDvdQBXKJ9ZjQCINyFOkxz4rCta6s2226SPAxH9CNrmvNsmamL7REElj1xqgzOuYja8YMAfJbe7PsifZA-zWz5P-W1IdVXNoM4E56-XKapHuERQsLT93gvwWThDQ

GET {{host}}/api/product HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

###
GET {{host}}/api/order HTTP/1.1