# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: src
        run: dotnet restore
      - name: Build
        working-directory: src/WebHost
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: src
        run: dotnet test AntSolution.sln --no-restore --verbosity normal
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
